MODULE = sign-verify-tests

DIRS += hmac-sign-verify-tests ecdsa-sign-verify-tests sha256-sign-verify-tests asn-encode-decode-tests

USEMODULE += hmac-sign-verify-tests ecdsa-sign-verify-tests sha256-sign-verify-tests asn-encode-decode-tests

include $(RIOTBASE)/Makefile.base
